# Generated by Django 4.1.3 on 2022-11-24 04:03

from django.db import migrations

def populate_status(apps, schemaeditor):
    statuses = {
        "to-do": "To Do",
        "in-progress": "In Progress",
        "done": "Done",
    }

    Status = apps.get_model("issues", "Status")
    for key, value in statuses.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()

def populate_priority(apps, schemaeditor):
    priorities = {
        "low": "Low",
        "medium": "Medium",
        "high": "High",
    }

    Priority = apps.get_model("issues", "Priority")
    for key, value in priorities.items():
        priority_obj = Priority(name=key, description=value)
        priority_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status),
        migrations.RunPython(populate_priority)
    ]

